# Generated by Django 3.1.7 on 2021-03-28 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(upload_to='static/')),
                ('bio', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='static/')),
                ('image_name', models.CharField(max_length=30)),
                ('image_caption', models.TextField(max_length=30)),
                ('likes', models.IntegerField(blank=True, null=True)),
                ('comments', models.TextField(max_length=50)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pixxie.profile')),
            ],
        ),
    ]
