# Generated by Django 3.1.7 on 2021-03-28 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixxie', '0004_auto_20210329_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
