# Generated by Django 3.1.7 on 2021-03-28 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profile_photo', models.ImageField(upload_to='profile_pic/')),
                ('Bio', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='images/')),
                ('Image_name', models.CharField(max_length=30)),
                ('Image_caption', models.TextField(max_length=30)),
                ('Likes', models.IntegerField()),
                ('Comments', models.TextField(max_length=50)),
                ('Profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pixxie.profile')),
            ],
        ),
    ]
