# Generated by Django 3.1.7 on 2021-03-28 23:14

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixxie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.CharField(default='username', max_length=50, verbose_name=django.contrib.auth.models.User),
        ),
    ]
