# Generated by Django 3.1.7 on 2021-03-30 19:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixxie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilephoto',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='profile photo'),
        ),
    ]
